#!/usr/bin/env python
#
# Copyright (c) 2015, Lawrence Livermore National Security, LLC.
# 
# Produced at the Lawrence Livermore National Laboratory
# 
# Written by Simone Atzeni (simone@cs.utah.edu), Ganesh Gopalakrishnan,
# Zvonimir Rakamari\'c Dong H. Ahn, Ignacio Laguna, Martin Schulz, and
# Gregory L. Lee
# 
# LLNL-CODE-676696
# 
# All rights reserved.
# 
# This file is part of Archer. For details, see
# https://github.com/soarlab/Archer. Please also read Archer/LICENSE.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the disclaimer below.
# 
# Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the disclaimer (as noted below) in
# the documentation and/or other materials provided with the
# distribution.
# 
# Neither the name of the LLNS/LLNL nor the names of its contributors
# may be used to endorse or promote products derived from this software
# without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE
# LIVERMORE NATIONAL SECURITY, LLC, THE U.S. DEPARTMENT OF ENERGY OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

import argparse
import errno
import json
import os
import re
import shutil
import signal
import subprocess
import sys

VERSION = '0.1'

# Working Dirs
WORKING_DIR = os.getcwd()
BUILD_LIST = '/tmp/buildList.ach'
LOGS_LIST = '/tmp/logsList.ach'
AR_FILE = '/tmp/ar.ach'
RANLIB_FILE = '/tmp/ranlib.ach'
LOGS_FLAG = '/tmp/clang-archer-log.ach'
buildFile = None
ARCHER_DIR = '.archer'
INCLUDE_LIST = []

# Extensions
POLLY_BC_EXT = ".nomp.bc"
OMP_BC_EXT = ".bc"
OPT_EXT = ".opt"
BC_EXT = ".bc"
LL_EXT = ".ll"
BL_EXT = ".bl"
O_EXT = ".o"
SOURCE_EXT = ['.c', '.cc', '.cpp', '.cxx']
OBJ_EXT = ['.o']
LIB_EXT = ['.a']
LOCAL_INCLUDE=[ "-I..", "-I../" ]

# Flags
ARCHER_DDA_FLAG = '-archer-dda'
LINKING=False
COMPILE_AND_LINK=False
KEEP_LOGS=False
NO_BLACKLISTING=False
OPT_FLAGS = [ "O0", "O1", "O2", "O3", "Os", "Oz" ]
OPT_FLAG="-O2"

def sanitizeFileName(filename):
    return filename.rsplit("/", 1)[-1]

def cleanLogs():
    if os.path.exists(LOGS_LIST):
        file = open(LOGS_LIST, "r")
        for line in file:
            shutil.rmtree(line.split('\n')[0], ignore_errors = True)
        file.close()
    os.system("rm -rf /tmp/*.ach")

def signal_handler(signal, frame):
    print('You pressed Ctrl+C!')
    if not KEEP_LOGS:
        try:
            cleanLogs()
        except OSError, e:
            pass
    else:
        with open(LOGS_FLAG, "w") as f:
            f.write('1')
            f.close()
    sys.exit(0)

class dotdict(dict):
    def __getattr__(self, attr):
        return self.get(attr)
    __setattr__= dict.__setitem__
    __delattr__= dict.__delitem__

def logPath(path):
    file = open(LOGS_LIST, "a")
    file.write(path + "\n")
    file.close()

def mkdir_p(path):
    try:
        os.makedirs(path)
    except OSError as e:
        if e.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else: raise

def compileErrorCheck(p, cmd, output):
    if p.returncode:
        print >> sys.stderr, output
        if not KEEP_LOGS:
            cleanLogs()
        else:
            with open(LOGS_FLAG, "w") as f:
                f.write('1')
                f.close()
        sys.exit("Archer encountered an error when invoking [" + cmd[0] + ''.join(' ' + s for s in cmd[1:]) + "].\nExiting...")

def executeCommand(cmd, args):
    if args is not None and args.debug:
        print('DEBUG-INFO: Path[' + os.getcwd() + "]")
        print('DEBUG-INFO: Command[' + cmd[0] + ''.join(' ' + s for s in cmd[1:]) + ']')
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = p.communicate()[0]
    regex = re.compile(r'\s+')
    if regex.sub('', output):
        print output
    compileErrorCheck(p, cmd, output)

def argumentsParser():
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument('-v', '--version', action='version', version='Archer ' + VERSION + '\nCopyright (C) 2015')
    parser.add_argument('-d', '--debug', action='store_true', help='Print the compiling commands')
    parser.add_argument('--log', action='store_true', help='Keep intermediate logs')
    parser.add_argument('-db', '--disable-blacklisting', action='store_true', help='Disable static analysis and apply ThreadSanitizer instrumentation to the entire program')
    parser.add_argument('-dsb', '--disable-sequential-blacklisting', action='store_true', help='Disable blacklisting of sequential code')
    parser.add_argument('-ddb', '--disable-dd-blacklisting', action='store_true', help='Disable blacklisting of loops with no data depdendency ')
    parser.add_argument('-cc', nargs='?', default='clang', help='Change the program used to compile and link the programs')
    parser.add_argument('--use-mpi', action='store_true', help='Link against MPI libraries')
    parser.add_argument('-mpicc', nargs='?', default='mpicc', help='Change the program used to compile and link the MPI programs')
    parser.add_argument('-opt', nargs='?', default='opt', help='Change the program used to optmize the programs')
    parser.add_argument('-link', nargs='?', default='llvm-link', help='Change the program used to link the byte code files')
    parser.add_argument('-dis', nargs='?', default='llvm-dis', help='Change the program used to disassemble the byte code files')
    parser.add_argument('-lib', nargs='?', default='LLVMArcher.so', help='Set the path where to find Archer libraries')
    parser.add_argument('--plugin-lib', nargs='?', default='ArcherPlugin.so', help='Set the path where to find Archer Plugin libraries')
    parser.add_argument('--openmp-include', nargs='?', default=os.path.dirname(os.path.realpath(__file__)).rsplit("/", 1)[0] + '/include', help='Set the path where to find OpenMP headers')
    # parser.add_argument('-mpi-include', nargs='?', default='', help='Set the path where to find MPI headers')
    # parser.add_argument('-mpi-lib', nargs='?', default='', help='Set the path where to find MPI libraries')
    # parser.add_argument('-g', action='store_true')
    parser.add_argument('-g', action='store_true', help='If the debugging flag is not present in the compilation command it will be added by default')
    action = parser.add_mutually_exclusive_group()
    action.add_argument('-O0', action='store_true', help='The optimization flags will be forced to \'-O0\' optimization level for analysis purposes')
    action.add_argument('-O1', action='store_true')
    action.add_argument('-O2', action='store_true')
    action.add_argument('-O3', action='store_true')
    action.add_argument('-Os', action='store_true')
    action.add_argument('-Oz', action='store_true')
    parser.add_argument('-fopenmp', action='store_true', help='OpenMP flag')
    parser.add_argument('-lomp', action='store_true', help='OpenMP library')
    parser.add_argument('-c', action='store_true', help='Only run preprocess, compile, and assemble steps')
    parser.add_argument('-o', nargs='?', default='a.out', help='Output filename')

    return parser

def archerBuild(args):
    print "Building..."

    mkdir_p('.archer')
    logPath(os.getcwd() + "/.archer")

    # Create ByteCode
    # No OpenMP Support
    clangCommand = [ args.cc ]
    clangCommand += [ "-Qunused-arguments", "-emit-llvm", "-O0", "-g", "-c", args.src, "-o", ARCHER_DIR + "/" + sanitizeFileName(args.o) + POLLY_BC_EXT, '-I' + args.openmp_include ]
    clangCommand.extend(args.unknown)

    executeCommand(clangCommand, args)
    # No OpenMP Support

    # OpenMP Support
    clangCommand = [ args.cc ]
    clangCommand += [ "-Qunused-arguments", "-emit-llvm", "-O0", "-g", "-fopenmp", "-c", args.src, "-o", ARCHER_DIR + "/" + sanitizeFileName(args.o) + OMP_BC_EXT, '-I' + args.openmp_include ]
    clangCommand.extend(args.unknown)
    executeCommand(clangCommand, args)
    # OpenMP Support
    # Create ByteCode

    # Changing dir to WORKING_DIR
    #os.chdir(ARCHER_DIR)

    # Polly Pass
    if(not args.disable_dd_blacklisting):
        optCommand = [ args.opt ]
        optCommand += [ '-mem2reg', ARCHER_DIR + "/" + sanitizeFileName(args.o) + POLLY_BC_EXT, "-o", ARCHER_DIR + "/" + sanitizeFileName(args.o) + POLLY_BC_EXT + OPT_EXT ]
        executeCommand(optCommand, args)

        optCommand = [ args.opt ]
        optCommand += [ '-S', '-polly-canonicalize', ARCHER_DIR + "/" + sanitizeFileName(args.o) + POLLY_BC_EXT + OPT_EXT, "-o", ARCHER_DIR + "/" + sanitizeFileName(args.o) + LL_EXT ]
        executeCommand(optCommand, args)

        optCommand = [ args.opt ]
        optCommand += [ '-polly-process-unprofitable', '-load', args.lib, ARCHER_DDA_FLAG, ARCHER_DIR + "/" + sanitizeFileName(args.o) + LL_EXT, "-o", ARCHER_DIR + "/" + sanitizeFileName(args.o) + "-optmized" + LL_EXT ]
        executeCommand(optCommand, args)
    # Polly Pass

    # Clang Plugin to find OpenMP constructs information
    clangCommand = [ args.cc ]
    clangCommand += [ "-Qunused-arguments", "-O0", "-g", "-fopenmp", "-c", args.src, '-I' + args.openmp_include ]
    clangCommand.extend(args.unknown)
    # lst = filter(lambda item: any(x in item for x in LOCAL_INCLUDE), args.unknown)
    # if lst:
    #     clangCommand += [ "-I../.."]
    # clangCommand.extend(INCLUDE_LIST)
    clangCommand += [ "-fsyntax-only", "-Xclang", "-load", "-Xclang", args.plugin_lib, "-Xclang", "-plugin", "-Xclang", "archer" ]
    executeCommand(clangCommand, args)
    # Clang Plugin to find OpenMP constructs information

def archerBuildNB(args):
    print "Building..."

    clangCommand = [ args.cc ]
    clangCommand += [ "-g", OPT_FLAG ]
    if(args.fopenmp):
        clangCommand += [ "-fopenmp" ]
    clangCommand += [ "-fsanitize=thread", "-c", args.src, '-I' + args.openmp_include]
    clangCommand.extend(args.unknown)
    executeCommand(clangCommand, args)

def archerLink(args):
    print "Linking..."

    # Creating and changing to WORKING_DIR
    mkdir_p('.archer')
    logPath(os.getcwd() + "/.archer")
    # os.chdir(ARCHER_DIR)

    builds = []
    bcLst = []
    # Read files to compile
    with open(BUILD_LIST, "r") as f:
        for line in f:
            lst = []
            spl = line.split(",",2)
            bc = spl[1].rsplit("/", 1)
            sp = spl[0].rsplit("/", 1)
            bcLst.append(sp[0] + "/" + ARCHER_DIR + "/" + bc[1] + BC_EXT)
            lst.append(spl[0])
            lst.append(spl[1])
            lst.append(dotdict(json.loads(spl[2])))
            builds.append(lst)
    # Read files to compile

    # Link byte code and run InstructionContext Pass
    linkCommand = [ args.link ]
    linkCommand += [ "-o", ARCHER_DIR + "/" + sanitizeFileName(args.o) + BC_EXT ]
    linkCommand.extend(bcLst)
    executeCommand(linkCommand, args)

    linkCommand = [ args.link ]
    linkCommand += [ "-f", ARCHER_DIR + "/" + sanitizeFileName(args.o) + BC_EXT, "-o", ARCHER_DIR + "/" + sanitizeFileName(args.o) + LL_EXT ]
    executeCommand(linkCommand, args)

    if(not args.disable_sequential_blacklisting):
        optCommand = [ args.opt ]
        optCommand += [ "-load", args.lib, "-archer-instruction-context", ARCHER_DIR + "/" + sanitizeFileName(args.o) + LL_EXT, "-o", ARCHER_DIR + "/" + sanitizeFileName(args.o) + BC_EXT ]
        executeCommand(optCommand, args)
    # Link byte code and run InstructionContext Pass

    # Create blacklists and compile with fsanitize
    if not COMPILE_AND_LINK:
        objFileList = []
        for item in builds:
            blCommand = [ "archer-bl" ]
            blCommand += [ item[0], "0" ]
            executeCommand(blCommand, args)

            arg = item[2]
            clangCommand = [ arg.cc ]
            clangCommand += [ "-g", OPT_FLAG ]
            if(arg.fopenmp):
                clangCommand += [ "-fopenmp" ]
            lst = item[0].rsplit("/", 1)
            blacklist = lst[0] + "/.archer/blacklists/" + lst[1] + BL_EXT
            clangCommand += [ "-fsanitize=thread", "-fsanitize-blacklist=" + blacklist, "-o", item[1], "-c", item[0], '-I' + args.openmp_include]
            clangCommand.extend(arg.unknown)
            executeCommand(clangCommand, args)
            objFileList.append(item[1])
    # Create blacklists and compile with fsanitize

    # Check if an ar command has been executed
    # if so execute them else link the object
    # files all together
    current_path = os.getcwd()
    if os.path.isfile(AR_FILE):
        try:
            # Create static libraries
            with open(AR_FILE, 'r') as file:
                for line in file:
                    lst = line.split(",", 1)
                    os.chdir(lst[0])
                    cmd = lst[1].split()
                    executeCommand(cmd, args)
        except IOError as e:
            print "clang-archer: No such file or directory or no read permissions"
        try:
            with open(RANLIB_FILE, 'r') as file:
                for line in file:
                    lst = line.split(",", 1)
                    os.chdir(lst[0])
                    cmd = lst[1].split()
                    executeCommand(cmd, args)
        except IOError as e:
            print "clang-archer: No such file or directory or no read permissions"


        # Link program
        os.chdir(current_path)
        if args.use_mpi:
            clangCommand = [ args.mpicc, '-cc=' + args.cc ]
        else:
            clangCommand = [ args.cc ]
        clangCommand += [ "-g", OPT_FLAG, "-fopenmp", "-fsanitize=thread", "-o", args.o, args.obj ]
        clangCommand.extend(args.unknown)
        # clangCommand += [ "-lomp" ]
        executeCommand(clangCommand, args)
    elif COMPILE_AND_LINK:
        os.chdir(current_path)
        if args.use_mpi:
            clangCommand = [ args.mpicc, '-cc=' + args.cc ]
        else:
            clangCommand = [ args.cc ]
        blCommand = [ "archer-bl" ]
        blCommand += [ args.src, "0" ]
        executeCommand(blCommand, args)
        blacklist = current_path + "/.archer/blacklists/" + args.src + BL_EXT

        clangCommand += [ "-g", OPT_FLAG, "-fopenmp", "-fsanitize=thread", "-fsanitize-blacklist=" + blacklist, "-o", args.o, args.src, '-I' + args.openmp_include ]
        clangCommand.extend(args.unknown)
        # clangCommand += [ "-lomp" ]
        executeCommand(clangCommand, args)
    else:
        os.chdir(current_path)
        if args.use_mpi:
            clangCommand = [ args.mpicc, '-cc=' + args.cc ]
        else:
            clangCommand = [ args.cc ]
        clangCommand += ["-g", OPT_FLAG, "-fopenmp", "-fsanitize=thread", "-o", args.o, args.obj ]
        clangCommand.extend(args.unknown)
        # clangCommand += [ "-lomp" ]
        executeCommand(clangCommand, args)

    if not KEEP_LOGS:
        cleanLogs()
    else:
        with open(LOGS_FLAG, "w") as f:
            f.write('1')
            f.close()

def archerLinkNB(args):
    print "Linking..."

    # Check if an ar command has been executed
    # if so execute them else link the object
    # files all together
    if COMPILE_AND_LINK:
        if args.use_mpi:
            clangCommand = [ args.mpicc, '-cc=' + args.cc ]
        else:
            clangCommand = [ args.cc ]
        clangCommand += [ "-g", OPT_FLAG, "-fopenmp", "-fsanitize=thread", "-o", args.o, args.src, '-I' + args.openmp_include ]
        clangCommand.extend(args.unknown)
        # clangCommand += [ "-lomp" ]
        executeCommand(clangCommand, args)
    else:
        if args.use_mpi:
            clangCommand = [ args.mpicc, '-cc=' + args.cc ]
        else:
            clangCommand = [ args.cc ]
        clangCommand += [ "-g", OPT_FLAG, "-fopenmp", "-fsanitize=thread", "-o", args.o, args.obj ]
        clangCommand.extend(args.unknown)
        # clangCommand += [ "-lomp" ]
        executeCommand(clangCommand, args)

    if not KEEP_LOGS:
        cleanLogs()
    else:
        with open(LOGS_FLAG, "w") as f:
            f.write('1')
            f.close()

if __name__ == '__main__':

    signal.signal(signal.SIGINT, signal_handler)

    if os.path.exists(LOGS_FLAG):
        with open(LOGS_FLAG, "r") as f:
            line = f.readline()
            if line == '1':
                cleanLogs()

    buildFile = open(BUILD_LIST, "a")

    # Create include dir list
    os.chdir("..")
    for dir in os.walk(os.getcwd()):
        for file in os.listdir(dir[0]):
            if(str(file).endswith(".h")):
                INCLUDE_LIST.append("-I" + dir[0])
                break
    os.chdir(WORKING_DIR)
    # Create include dir list

    # parse command line arguments
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter, description='Compile your program with Archer support, a data race detector for OpenMP programs.', parents=[argumentsParser()])
    args, unknown = parser.parse_known_args()

    KEEP_LOGS = args.log
    NO_BLACKLISTING = args.disable_blacklisting

    # find source file .c, .cc, .cpp, .cxx in unknown arguments
    if args.c is False:
        for arg in unknown:
            if any(arg.endswith(ext) for ext in SOURCE_EXT):
                args.__dict__['src'] = arg
                unknown.remove(arg)
                args.__dict__['unknown'] = unknown
                COMPILE_AND_LINK=True
                break
        if 'src' not in args.__dict__:
            for arg in unknown:
                if any(arg.endswith(ext) for ext in OBJ_EXT):
                    args.__dict__['src'] = None
                    args.__dict__['obj'] = arg
                    unknown.remove(arg)
                    args.__dict__['unknown'] = unknown
                    LINKING=True
                    break
            else:
                sys.exit("Archer encountered an error when parsing parameters.\nExiting...")
    else:
        for arg in unknown:
            if any(arg.endswith(ext) for ext in SOURCE_EXT):
                args.__dict__['src'] = arg
                unknown.remove(arg)
                break
        args.__dict__['unknown'] = unknown

        filename = args.src
        args.o = filename[::-1].split('.', 1)[1][::-1] + ".o"

    # Keep list of compiled file
    if args.src is not None:
        buildFile.write(os.path.abspath(args.src) + "," + os.path.abspath(args.o) + "," + json.dumps(args.__dict__) + '\n')
    buildFile.close()

    if KEEP_LOGS:
        if not os.path.exists(LOGS_FLAG):
            with open(LOGS_FLAG, "w") as f:
                f.write('0')
                f.close()

    # args.openmp_include = "-I" + args.openmp_include if (args.openmp_include is not '') else ''
    # args.MPI_INCLUDE = "-I" + args.MPI_INCLUDE if (args.MPI_INCLUDE is not '') else ''

    # Check optimization flag
    for arg in OPT_FLAGS:
        if args.__dict__[arg]:
            OPT_FLAG = "-" + arg
            break

    if NO_BLACKLISTING:
        if COMPILE_AND_LINK:
            print "Compiling and Linking"
            archerLinkNB(args)
        else:
            if not LINKING:
                archerBuildNB(args)
            else:
                archerLinkNB(args)
    else:
        if COMPILE_AND_LINK:
            print "Compiling and Linking"
            archerBuild(args)
            archerLink(args)
        else:
            if not LINKING:
                open('/tmp/ar_archer', 'w').close()
                open('/tmp/ranlib_archer', 'w').close()
                archerBuild(args)
            else:
                os.remove("/tmp/ar_archer")
                os.remove("/tmp/ranlib_archer")
                archerLink(args)
