#!/usr/bin/env python 
#
# Copyright (c) 2015, Lawrence Livermore National Security, LLC.
# 
# Produced at the Lawrence Livermore National Laboratory
# 
# Written by Simone Atzeni (simone@cs.utah.edu), Ganesh Gopalakrishnan,
# Zvonimir Rakamari\'c Dong H. Ahn, Ignacio Laguna, Martin Schulz, and
# Gregory L. Lee
# 
# LLNL-CODE-676696
# 
# All rights reserved.
# 
# This file is part of Archer. For details, see
# https://github.com/soarlab/Archer. Please also read Archer/LICENSE.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the disclaimer below.
# 
# Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the disclaimer (as noted below) in
# the documentation and/or other materials provided with the
# distribution.
# 
# Neither the name of the LLNS/LLNL nor the names of its contributors
# may be used to endorse or promote products derived from this software
# without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE
# LIVERMORE NATIONAL SECURITY, LLC, THE U.S. DEPARTMENT OF ENERGY OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

import errno
import os
import sys
import subprocess
import hashlib

# ppid = int(os.popen("ps -p %d -oppid=" % os.getppid()).read().strip())
# parent = os.popen("ps -p %d -o cmd | grep -v CMD" % os.getppid()).read().strip()
# parent = os.popen("ps -p %d -o comm=" % os.getppid()).read().strip()
# parent = os.popen("ps -p %d -o cmd | grep -v CMD" % os.getppid()).read().strip()

if(not os.path.isfile("/tmp/ranlib_archer")):
    # Normal execution of ranlib
    sys.argv[0] = '/usr/bin/ranlib'
    p = subprocess.Popen(sys.argv, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = p.communicate()[0]
    print output
else:
    # Intercepted by clang-archer
    command = os.getcwd() + "," + sys.argv[0] + ''.join(' ' + s for s in sys.argv[1:])
    # h = hashlib.new('ripemd160')
    # COMMAND_LOG = '/tmp/ranlib_' + h.hexdigest() + '.ach'
    COMMAND_LOG = '/tmp/ranlib.ach'
    
    with open(COMMAND_LOG, "a") as f:
        f.write(command + "\n")
        f.close()
